# Generated by Django 5.1.1 on 2024-09-27 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0002_macarona'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='pizza_type',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='S', max_length=1),
        ),
    ]
